/* MotoFFP em bloco unico para m68k-elf-as (MRI) */

            INCLUDE ffp\FFP10TBL.asm
            INCLUDE ffp\FFPDBF.asm
            INCLUDE ffp\FFPAFP.asm
            INCLUDE ffp\FFPFPA.asm
            INCLUDE ffp\FFPABS.asm
            INCLUDE ffp\FFPADD.asm
            INCLUDE ffp\FFPARND.asm
            INCLUDE ffp\FFPATAN.asm
            INCLUDE ffp\FFPCMP.asm
            INCLUDE ffp\FFPDIV.asm
            INCLUDE ffp\FFPEXP.asm
            INCLUDE ffp\FFPFPI.asm
            INCLUDE ffp\FFPIFP.asm
            INCLUDE ffp\FFPLOG.asm
            INCLUDE ffp\FFPMUL2.asm
            INCLUDE ffp\FFPPWR.asm
            INCLUDE ffp\FFPSIN.asm
            INCLUDE ffp\FFPSINH.asm
            INCLUDE ffp\FFPSQRT.asm
            INCLUDE ffp\FFPHTHET.asm
            INCLUDE ffp\FFPTHETA.asm
            INCLUDE ffp\FFPTNORM.asm
